FROM ruby:alpine

RUN gem install waithook

ARG WAITHOOK_UUID
ARG WAITHOOK_FORWARD

ENV WAITHOOK_UUID=${WAITHOOK_UUID}
ENV WAITHOOK_FORWARD=${WAITHOOK_FORWARD}
ENV PATH=$PATH:${GEM_PATHS}
CMD waithook waithook.com/${WAITHOOK_UUID} -v --forward ${WAITHOOK_FORWARD}
